### ISSUE TITLE
bank-account: developing new test case 

### ISSUE THREAD

**Issue by rpottsoh** [rpottsoh/My-Exercism-Solutions#1]
@kotp, I have pushed my WIP changes to [here](https://github.com/rpottsoh/exercism-Delphi/blob/devlopment/BankAccount/bank-account/uBankAccountTests.pas).  The last two test cases are what I have added.  The second to the last works.  It is essentially the same as the published test but rather than adjusting the balance it just opens and closes the account a bunch of times.  The last test case is supposed to be a combination of the prior two tests.  This last test case is broken.  I have some other ideas I am going to pursue but I thought I would put it up here.  It is usually helpful to bounce ideas off another person.

**Comment by kotp** [comment]
Test seems pretty good, but as discussed, may end up with occasional false positives.
